var hierarchy =
[
    [ "agent.Agent", "classagent_1_1_agent.html", null ],
    [ "onsite_llm.Chat_GPT", "classonsite__llm_1_1_chat___g_p_t.html", null ],
    [ "guided_completion.ChoicesCompletion", "classguided__completion_1_1_choices_completion.html", null ],
    [ "client.Client", "classclient_1_1_client.html", null ],
    [ "torch.utils.data.Dataset", null, [
      [ "onsite_llm.FinetuningDataset", "classonsite__llm_1_1_finetuning_dataset.html", null ],
      [ "onsite_llm.FinetuningDataset", "classonsite__llm_1_1_finetuning_dataset.html", null ]
    ] ],
    [ "data_synthesis.DataSynthesis", "classdata__synthesis_1_1_data_synthesis.html", null ],
    [ "onsite_llm.GPT3", "classonsite__llm_1_1_g_p_t3.html", null ],
    [ "guided_completion.GrammarCompletion", "classguided__completion_1_1_grammar_completion.html", null ],
    [ "optimize.local_ephemeral", "classoptimize_1_1local__ephemeral.html", null ],
    [ "optimize.Optimizer", "classoptimize_1_1_optimizer.html", [
      [ "optimize.HostedOptimizer", "classoptimize_1_1_hosted_optimizer.html", null ],
      [ "optimize.HostedOptimizer", "classoptimize_1_1_hosted_optimizer.html", null ],
      [ "optimize.LocalOptimizer", "classoptimize_1_1_local_optimizer.html", null ],
      [ "optimize.LocalOptimizer", "classoptimize_1_1_local_optimizer.html", null ]
    ] ],
    [ "ram.RAMLogger", "classram_1_1_r_a_m_logger.html", null ],
    [ "guided_completion.RegexCompletion", "classguided__completion_1_1_regex_completion.html", null ],
    [ "eval_finetuned.suppress_output", "classeval__finetuned_1_1suppress__output.html", null ],
    [ "test_agent.suppress_output", "classtest__agent_1_1suppress__output.html", null ],
    [ "guided_completion.TypeCompletion", "classguided__completion_1_1_type_completion.html", null ],
    [ "ABC", null, [
      [ "guided_completion.GrammarConstraint", "classguided__completion_1_1_grammar_constraint.html", [
        [ "guided_completion.JSONConstraint", "classguided__completion_1_1_j_s_o_n_constraint.html", null ],
        [ "guided_completion.JSONConstraint", "classguided__completion_1_1_j_s_o_n_constraint.html", null ],
        [ "guided_completion.PythonConstraint", "classguided__completion_1_1_python_constraint.html", null ],
        [ "guided_completion.PythonConstraint", "classguided__completion_1_1_python_constraint.html", null ]
      ] ],
      [ "guided_completion.GrammarConstraint", "classguided__completion_1_1_grammar_constraint.html", null ],
      [ "onsite_llm.Base_Onsite_LLM", "classonsite__llm_1_1_base___onsite___l_l_m.html", [
        [ "onsite_llm.Small_Code_LLama", "classonsite__llm_1_1_small___code___l_lama.html", null ],
        [ "onsite_llm.Small_Code_LLama", "classonsite__llm_1_1_small___code___l_lama.html", null ],
        [ "onsite_llm.Small_Local_BERT", "classonsite__llm_1_1_small___local___b_e_r_t.html", null ],
        [ "onsite_llm.Small_Local_BERT", "classonsite__llm_1_1_small___local___b_e_r_t.html", null ],
        [ "onsite_llm.Small_Local_Bloom", "classonsite__llm_1_1_small___local___bloom.html", null ],
        [ "onsite_llm.Small_Local_Bloom", "classonsite__llm_1_1_small___local___bloom.html", null ],
        [ "onsite_llm.Small_Local_Flan_T5", "classonsite__llm_1_1_small___local___flan___t5.html", null ],
        [ "onsite_llm.Small_Local_Flan_T5", "classonsite__llm_1_1_small___local___flan___t5.html", null ],
        [ "onsite_llm.Small_Local_LLama", "classonsite__llm_1_1_small___local___l_lama.html", null ],
        [ "onsite_llm.Small_Local_LLama", "classonsite__llm_1_1_small___local___l_lama.html", null ],
        [ "onsite_llm.Small_Local_Neo", "classonsite__llm_1_1_small___local___neo.html", null ],
        [ "onsite_llm.Small_Local_Neo", "classonsite__llm_1_1_small___local___neo.html", null ],
        [ "onsite_llm.Small_Local_OPT", "classonsite__llm_1_1_small___local___o_p_t.html", null ],
        [ "onsite_llm.Small_Local_OPT", "classonsite__llm_1_1_small___local___o_p_t.html", null ],
        [ "onsite_llm.Small_Local_OpenLLama", "classonsite__llm_1_1_small___local___open_l_lama.html", null ],
        [ "onsite_llm.Small_Local_OpenLLama", "classonsite__llm_1_1_small___local___open_l_lama.html", null ],
        [ "onsite_llm.Small_Local_Pythia", "classonsite__llm_1_1_small___local___pythia.html", null ],
        [ "onsite_llm.Small_Local_Pythia", "classonsite__llm_1_1_small___local___pythia.html", null ]
      ] ],
      [ "onsite_llm.Base_Onsite_LLM", "classonsite__llm_1_1_base___onsite___l_l_m.html", null ]
    ] ],
    [ "Enum", null, [
      [ "typings.DecisionStep", "classtypings_1_1_decision_step.html", null ],
      [ "typings.DecisionStep", "classtypings_1_1_decision_step.html", null ],
      [ "typings.DefaultTools", "classtypings_1_1_default_tools.html", null ],
      [ "typings.DefaultTools", "classtypings_1_1_default_tools.html", null ],
      [ "typings.DefaultTrainingTools", "classtypings_1_1_default_training_tools.html", null ],
      [ "typings.DefaultTrainingTools", "classtypings_1_1_default_training_tools.html", null ],
      [ "typings.LLMCallType", "classtypings_1_1_l_l_m_call_type.html", null ],
      [ "typings.LLMCallType", "classtypings_1_1_l_l_m_call_type.html", null ],
      [ "typings.OpenAIModel", "classtypings_1_1_open_a_i_model.html", null ],
      [ "typings.OpenAIModel", "classtypings_1_1_open_a_i_model.html", null ],
      [ "typings_llm.DecisionStep", "classtypings__llm_1_1_decision_step.html", null ],
      [ "typings_llm.DecisionStep", "classtypings__llm_1_1_decision_step.html", null ],
      [ "typings_llm.DefaultTools", "classtypings__llm_1_1_default_tools.html", null ],
      [ "typings_llm.DefaultTools", "classtypings__llm_1_1_default_tools.html", null ],
      [ "typings_llm.DefaultTrainingTools", "classtypings__llm_1_1_default_training_tools.html", null ],
      [ "typings_llm.DefaultTrainingTools", "classtypings__llm_1_1_default_training_tools.html", null ],
      [ "typings_llm.LLMCallType", "classtypings__llm_1_1_l_l_m_call_type.html", null ],
      [ "typings_llm.LLMCallType", "classtypings__llm_1_1_l_l_m_call_type.html", null ],
      [ "typings_llm.OpenAIModel", "classtypings__llm_1_1_open_a_i_model.html", null ],
      [ "typings_llm.OpenAIModel", "classtypings__llm_1_1_open_a_i_model.html", null ]
    ] ],
    [ "LogitsProcessor", null, [
      [ "guided_completion.GrammarLogitsProcessor", "classguided__completion_1_1_grammar_logits_processor.html", null ],
      [ "guided_completion.GrammarLogitsProcessor", "classguided__completion_1_1_grammar_logits_processor.html", null ]
    ] ],
    [ "TypedDict", null, [
      [ "typings.AnswerFromMemoryModelData", "classtypings_1_1_answer_from_memory_model_data.html", null ],
      [ "typings.AnswerFromMemoryModelData", "classtypings_1_1_answer_from_memory_model_data.html", null ],
      [ "typings.AnswerInMemoryModel", "classtypings_1_1_answer_in_memory_model.html", null ],
      [ "typings.AnswerInMemoryModel", "classtypings_1_1_answer_in_memory_model.html", null ],
      [ "typings.AnswerInMemoryModelData", "classtypings_1_1_answer_in_memory_model_data.html", null ],
      [ "typings.AnswerInMemoryModelData", "classtypings_1_1_answer_in_memory_model_data.html", null ],
      [ "typings.DebugCalls", "classtypings_1_1_debug_calls.html", null ],
      [ "typings.DebugCalls", "classtypings_1_1_debug_calls.html", null ],
      [ "typings.LLMCallParams", "classtypings_1_1_l_l_m_call_params.html", null ],
      [ "typings.LLMCallParams", "classtypings_1_1_l_l_m_call_params.html", null ],
      [ "typings.LLMTrainingResult", "classtypings_1_1_l_l_m_training_result.html", null ],
      [ "typings.LLMTrainingResult", "classtypings_1_1_l_l_m_training_result.html", null ],
      [ "typings.LLMTrainingResultMeta", "classtypings_1_1_l_l_m_training_result_meta.html", null ],
      [ "typings.LLMTrainingResultMeta", "classtypings_1_1_l_l_m_training_result_meta.html", null ],
      [ "typings.PromptModelEntry", "classtypings_1_1_prompt_model_entry.html", null ],
      [ "typings.PromptModelEntry", "classtypings_1_1_prompt_model_entry.html", null ],
      [ "typings.QuestionSplitInputModel", "classtypings_1_1_question_split_input_model.html", null ],
      [ "typings.QuestionSplitInputModel", "classtypings_1_1_question_split_input_model.html", null ],
      [ "typings.QuestionSplitModelData", "classtypings_1_1_question_split_model_data.html", null ],
      [ "typings.QuestionSplitModelData", "classtypings_1_1_question_split_model_data.html", null ],
      [ "typings.QuestionSplitModelJSONData", "classtypings_1_1_question_split_model_j_s_o_n_data.html", null ],
      [ "typings.QuestionSplitModelJSONData", "classtypings_1_1_question_split_model_j_s_o_n_data.html", null ],
      [ "typings.SingleTool", "classtypings_1_1_single_tool.html", null ],
      [ "typings.SingleTool", "classtypings_1_1_single_tool.html", null ],
      [ "typings.ToolInputModel", "classtypings_1_1_tool_input_model.html", null ],
      [ "typings.ToolInputModel", "classtypings_1_1_tool_input_model.html", null ],
      [ "typings.ToolInputModelData", "classtypings_1_1_tool_input_model_data.html", null ],
      [ "typings.ToolInputModelData", "classtypings_1_1_tool_input_model_data.html", null ],
      [ "typings.ToolInputModelJSONData", "classtypings_1_1_tool_input_model_j_s_o_n_data.html", null ],
      [ "typings.ToolInputModelJSONData", "classtypings_1_1_tool_input_model_j_s_o_n_data.html", null ],
      [ "typings.ToolTypeArgs", "classtypings_1_1_tool_type_args.html", null ],
      [ "typings.ToolTypeArgs", "classtypings_1_1_tool_type_args.html", null ],
      [ "typings.ToolpickerInputModel", "classtypings_1_1_toolpicker_input_model.html", null ],
      [ "typings.ToolpickerInputModel", "classtypings_1_1_toolpicker_input_model.html", null ],
      [ "typings.ToolpickerInputModelData", "classtypings_1_1_toolpicker_input_model_data.html", null ],
      [ "typings.ToolpickerInputModelData", "classtypings_1_1_toolpicker_input_model_data.html", null ],
      [ "typings.ToolpickerInputModelJSONData", "classtypings_1_1_toolpicker_input_model_j_s_o_n_data.html", null ],
      [ "typings.ToolpickerInputModelJSONData", "classtypings_1_1_toolpicker_input_model_j_s_o_n_data.html", null ],
      [ "typings_llm.AnswerFromMemoryModelData", "classtypings__llm_1_1_answer_from_memory_model_data.html", null ],
      [ "typings_llm.AnswerFromMemoryModelData", "classtypings__llm_1_1_answer_from_memory_model_data.html", null ],
      [ "typings_llm.AnswerInMemoryModel", "classtypings__llm_1_1_answer_in_memory_model.html", null ],
      [ "typings_llm.AnswerInMemoryModel", "classtypings__llm_1_1_answer_in_memory_model.html", null ],
      [ "typings_llm.AnswerInMemoryModelData", "classtypings__llm_1_1_answer_in_memory_model_data.html", null ],
      [ "typings_llm.AnswerInMemoryModelData", "classtypings__llm_1_1_answer_in_memory_model_data.html", null ],
      [ "typings_llm.DebugCalls", "classtypings__llm_1_1_debug_calls.html", null ],
      [ "typings_llm.DebugCalls", "classtypings__llm_1_1_debug_calls.html", null ],
      [ "typings_llm.LLMCallParams", "classtypings__llm_1_1_l_l_m_call_params.html", null ],
      [ "typings_llm.LLMCallParams", "classtypings__llm_1_1_l_l_m_call_params.html", null ],
      [ "typings_llm.LLMTrainingResult", "classtypings__llm_1_1_l_l_m_training_result.html", null ],
      [ "typings_llm.LLMTrainingResult", "classtypings__llm_1_1_l_l_m_training_result.html", null ],
      [ "typings_llm.LLMTrainingResultMeta", "classtypings__llm_1_1_l_l_m_training_result_meta.html", null ],
      [ "typings_llm.LLMTrainingResultMeta", "classtypings__llm_1_1_l_l_m_training_result_meta.html", null ],
      [ "typings_llm.PromptModelEntry", "classtypings__llm_1_1_prompt_model_entry.html", null ],
      [ "typings_llm.PromptModelEntry", "classtypings__llm_1_1_prompt_model_entry.html", null ],
      [ "typings_llm.QuestionSplitInputModel", "classtypings__llm_1_1_question_split_input_model.html", null ],
      [ "typings_llm.QuestionSplitInputModel", "classtypings__llm_1_1_question_split_input_model.html", null ],
      [ "typings_llm.QuestionSplitModelData", "classtypings__llm_1_1_question_split_model_data.html", null ],
      [ "typings_llm.QuestionSplitModelData", "classtypings__llm_1_1_question_split_model_data.html", null ],
      [ "typings_llm.QuestionSplitModelJSONData", "classtypings__llm_1_1_question_split_model_j_s_o_n_data.html", null ],
      [ "typings_llm.QuestionSplitModelJSONData", "classtypings__llm_1_1_question_split_model_j_s_o_n_data.html", null ],
      [ "typings_llm.SingleTool", "classtypings__llm_1_1_single_tool.html", null ],
      [ "typings_llm.SingleTool", "classtypings__llm_1_1_single_tool.html", null ],
      [ "typings_llm.ToolInputModel", "classtypings__llm_1_1_tool_input_model.html", null ],
      [ "typings_llm.ToolInputModel", "classtypings__llm_1_1_tool_input_model.html", null ],
      [ "typings_llm.ToolInputModelData", "classtypings__llm_1_1_tool_input_model_data.html", null ],
      [ "typings_llm.ToolInputModelData", "classtypings__llm_1_1_tool_input_model_data.html", null ],
      [ "typings_llm.ToolInputModelJSONData", "classtypings__llm_1_1_tool_input_model_j_s_o_n_data.html", null ],
      [ "typings_llm.ToolInputModelJSONData", "classtypings__llm_1_1_tool_input_model_j_s_o_n_data.html", null ],
      [ "typings_llm.ToolTypeArgs", "classtypings__llm_1_1_tool_type_args.html", null ],
      [ "typings_llm.ToolTypeArgs", "classtypings__llm_1_1_tool_type_args.html", null ],
      [ "typings_llm.ToolpickerInputModel", "classtypings__llm_1_1_toolpicker_input_model.html", null ],
      [ "typings_llm.ToolpickerInputModel", "classtypings__llm_1_1_toolpicker_input_model.html", null ],
      [ "typings_llm.ToolpickerInputModelData", "classtypings__llm_1_1_toolpicker_input_model_data.html", null ],
      [ "typings_llm.ToolpickerInputModelData", "classtypings__llm_1_1_toolpicker_input_model_data.html", null ],
      [ "typings_llm.ToolpickerInputModelJSONData", "classtypings__llm_1_1_toolpicker_input_model_j_s_o_n_data.html", null ],
      [ "typings_llm.ToolpickerInputModelJSONData", "classtypings__llm_1_1_toolpicker_input_model_j_s_o_n_data.html", null ]
    ] ]
];