var namespacetypings =
[
    [ "AnswerFromMemoryModelData", "classtypings_1_1_answer_from_memory_model_data.html", null ],
    [ "AnswerInMemoryModel", "classtypings_1_1_answer_in_memory_model.html", null ],
    [ "AnswerInMemoryModelData", "classtypings_1_1_answer_in_memory_model_data.html", null ],
    [ "DebugCalls", "classtypings_1_1_debug_calls.html", null ],
    [ "DecisionStep", "classtypings_1_1_decision_step.html", null ],
    [ "DefaultTools", "classtypings_1_1_default_tools.html", null ],
    [ "DefaultTrainingTools", "classtypings_1_1_default_training_tools.html", null ],
    [ "LLMCallParams", "classtypings_1_1_l_l_m_call_params.html", null ],
    [ "LLMCallType", "classtypings_1_1_l_l_m_call_type.html", null ],
    [ "LLMTrainingResult", "classtypings_1_1_l_l_m_training_result.html", null ],
    [ "LLMTrainingResultMeta", "classtypings_1_1_l_l_m_training_result_meta.html", null ],
    [ "OpenAIModel", "classtypings_1_1_open_a_i_model.html", null ],
    [ "PromptModelEntry", "classtypings_1_1_prompt_model_entry.html", null ],
    [ "QuestionSplitInputModel", "classtypings_1_1_question_split_input_model.html", null ],
    [ "QuestionSplitModelData", "classtypings_1_1_question_split_model_data.html", null ],
    [ "QuestionSplitModelJSONData", "classtypings_1_1_question_split_model_j_s_o_n_data.html", null ],
    [ "SingleTool", "classtypings_1_1_single_tool.html", null ],
    [ "ToolInputModel", "classtypings_1_1_tool_input_model.html", null ],
    [ "ToolInputModelData", "classtypings_1_1_tool_input_model_data.html", null ],
    [ "ToolInputModelJSONData", "classtypings_1_1_tool_input_model_j_s_o_n_data.html", null ],
    [ "ToolpickerInputModel", "classtypings_1_1_toolpicker_input_model.html", null ],
    [ "ToolpickerInputModelData", "classtypings_1_1_toolpicker_input_model_data.html", null ],
    [ "ToolpickerInputModelJSONData", "classtypings_1_1_toolpicker_input_model_j_s_o_n_data.html", null ],
    [ "ToolTypeArgs", "classtypings_1_1_tool_type_args.html", null ],
    [ "ALL_TOOLS_MAP", "namespacetypings.html#a27d044ce738ab7587b778cbd2c2d6cc0", null ],
    [ "DebugCallList", "namespacetypings.html#a9bcb080a5f8d509dad54e75e54e18e0f", null ],
    [ "EnumeratedToolList", "namespacetypings.html#a6caaeb3c3388865069fba505e4cf4678", null ],
    [ "LLMCallReturnType", "namespacetypings.html#a6399e77a510437d455659f08a3ed9e18", null ],
    [ "LLModels", "namespacetypings.html#ae86029216b3d7cca689d6227cef433c3", null ],
    [ "ToolList", "namespacetypings.html#aeb85fbcb424614940185547d1e7cf517", null ],
    [ "TupleList", "namespacetypings.html#ab190d93e482089949510c9ed7be7254a", null ]
];