# Generated by Django 4.2.6 on 2023-10-28 23:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languagemodel',
            old_name='model',
            new_name='model_name',
        ),
    ]
