# Generated by Django 4.2.6 on 2023-10-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_rename_model_languagemodel_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagemodel',
            name='response',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
